INSERT INTO USER1 (ID, NAME, NICK_NAME, PASSWORD, AGE, COMPANY, FRIENDS_COUNT)
VALUES (1001, 'Sergey', 'serg', '123', 22, 'TDR', 2);
INSERT INTO USER1 (ID, NAME, NICK_NAME, PASSWORD, AGE, COMPANY, FRIENDS_COUNT)
VALUES (1002, 'Nikita', 'nik', '1234', 62, 'TDD', 222);
INSERT INTO USER1 (ID, NAME, NICK_NAME, PASSWORD, AGE, COMPANY, FRIENDS_COUNT)
VALUES (1003, 'Oleg', '0leg', 'qwerty', 32, 'TD000', 22);
INSERT INTO USER1 (ID, NAME, NICK_NAME, PASSWORD, AGE, COMPANY, FRIENDS_COUNT)
VALUES (1004, 'Yan', '--yan--', 'asdfg', 23, '000 Toser', 5552);
INSERT INTO USER1 (ID, NAME, NICK_NAME, PASSWORD, AGE, COMPANY, FRIENDS_COUNT)
VALUES (1005, 'Yulii', 'YULII', 'zxcvb', 28, 'TOV Nika', 252);
INSERT INTO USER1 (ID, NAME, NICK_NAME, PASSWORD, AGE, COMPANY, FRIENDS_COUNT)
VALUES (1006, 'Igor', '<igor>', '00000', 43, 'Plore', 525);
INSERT INTO USER1 (ID, NAME, NICK_NAME, PASSWORD, AGE, COMPANY, FRIENDS_COUNT)
VALUES (1007, 'Andrii', '=ANDRE=', '12345678', 12, 'Gop', 242);
INSERT INTO USER1 (ID, NAME, NICK_NAME, PASSWORD, AGE, COMPANY, FRIENDS_COUNT)
VALUES (1008, 'Pasha', 'pasha', 'qqqqqqqqq', 29, 'Fox', 33);
INSERT INTO USER1 (ID, NAME, NICK_NAME, PASSWORD, AGE, COMPANY, FRIENDS_COUNT)
VALUES (1009, 'Alrxandr', 'Alex', 'poiuytre', 66, 'Nokia', 266);
INSERT INTO USER1 (ID, NAME, NICK_NAME, PASSWORD, AGE, COMPANY, FRIENDS_COUNT)
VALUES (1010, 'Olexii', 'Lexa', 'okmijnuh', 55, 'Hollandia', 772);

SELECT ID FROM USER1

SELECT * FROM USER1

CREATE TABLE USERS (
  ID NUMBER NOT NULL,
  CONSTRAINT USERS_PK PRIMARY KEY (ID),
  TYPE NVARCHAR2(20) NOT NULL,
  EMAIL NVARCHAR2(20) NOT NULL,
  PASSWORD NVARCHAR2(20) NOT NULL,
  USER_NAME NVARCHAR2(10),
  PHONE NVARCHAR2(20),
	CITY NVARCHAR2(30),
	DATE_REGISTERED TIMESTAMP NOT NULL,
	LAST_ACTIVE_DATE TIMESTAMP NOT NULL,
	IS_ACTIVE NUMBER NOT NULL,
  ATTRIBUTES CLOB
	);
  
  CREATE SEQUENCE USERS_SEQ MINVALUE 1000 MAXVALUE 10000000000 START WITH 1001 INCREMENT BY 1;
  
  SELECT COUNT(ID) FROM USER1
  
   SELECT * FROM USER1
   
   SELECT COUNT(ID) FROM USER1 WHERE FRIENDS_COUNT > 10
   
   SELECT COUNT(ID) FROM USER1 WHERE AGE > 21
   
   SELECT * FROM USER1 WHERE NAME='Sergey' OR NAME='Olexii'
  
  select * from user1
  
  select * from Users where email = 'test@test.com' or user_Name = is null
  
  UPDATE USER1 SET COMPANY = 'Google' WHERE COMPANY = 'TDR';
  
  UPDATE USER1 SET COMPANY = 'AMAZON' WHERE COMPANY = 'TDD';
  
  SELECT COUNT(ID) FROM USER1 WHERE COMPANY = 'AMAZON' OR COMPANY = 'Google'
  
  UPDATE USER1 SET COMPANY = NULL WHERE COMPANY = 'Gop';
  
  ALTER TABLE USER1 MODIFY CITY NVARCHAR2(15) NOT NULL
  
  UPDATE USER1 SET CITY='1' WHERE CITY IS NULL
  
  